<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-0IMO270T" failures="1" tests="3" name="runner.TestProjRunner" time="81.508" errors="0" timestamp="2023-03-21T15:45:40 EDT" skipped="0">
  <testcase classname="runner.TestProjRunner" name="runScenario" time="38.507"/>
  <system-out/>
  <testcase classname="runner.TestProjRunner" name="runScenario" time="20.669"/>
  <system-out/>
  <testcase classname="runner.TestProjRunner" name="runScenario" time="22.332">
    <failure message="expected [b] but found [a]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.StepDefForTestProj.this_test_should_fail(StepDefForTestProj.java:51)
at âœ½.this test should fail(file:///C:/Users/Usman/IdeaProjects/BDDFrameworkMar23/src/test/resources/demoLogin.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.TestProjRunner -->
